services:
  - type: web
    name: financas-pessoais
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    env: python
    python:
      version: 3.9.13